package webhooksigning

import "testing"

func TestSignPayloadMatchesTypeScriptCoreFixture(t *testing.T) {
	body := `{"id":"whd_delivery-1_1","type":"email.delivered","created_at":"2026-04-28T00:00:00.000Z","data":{"smtpResponse":"250 ok","nested":{"ok":true,"count":2}}}`

	signature := SignPayload("whsec_test_secret", "whd_delivery-1_1", "1777334400", body)

	// Generated by packages/core/src/webhook-signing.ts with the same fixture.
	const expected = "v1,v+tENYEHZ2JtXjDD1cSbGyDUqtXaMm8LvmoySIyHbdg="
	if signature != expected {
		t.Fatalf("expected TypeScript fixture signature %q, got %q", expected, signature)
	}
}

func TestBuildSignedHeadersMatchesDispatcherHeaderNames(t *testing.T) {
	body := `{"hello":"world"}`
	headers := BuildSignedHeaders(
		"plain_secret",
		"msg_01JZPARITY0000000000000000",
		"1777334401",
		body,
	)

	if headers.ID != "msg_01JZPARITY0000000000000000" {
		t.Fatalf("expected svix id to be preserved, got %q", headers.ID)
	}
	if headers.Timestamp != "1777334401" {
		t.Fatalf("expected timestamp to be preserved, got %q", headers.Timestamp)
	}
	if headers.Signature != "v1,WiBMtB++EOXU4IlqOzWvhJBBIlqdtBB+O1X3D3WrXCI=" {
		t.Fatalf("unexpected signature %q", headers.Signature)
	}

	mapped := headers.Map()
	assertHeader(t, mapped, SvixIDHeader, headers.ID)
	assertHeader(t, mapped, SvixTimestampHeader, headers.Timestamp)
	assertHeader(t, mapped, SvixSignatureHeader, headers.Signature)
}

func TestStripSigningSecretPrefixMatchesTypeScriptReplace(t *testing.T) {
	stripped := stripSigningSecretPrefix("whsec_first_whsec_second")
	if stripped != "first_whsec_second" {
		t.Fatalf("expected only the first whsec_ occurrence to be stripped, got %q", stripped)
	}
}

func assertHeader(t *testing.T, mapped map[string]string, name string, expected string) {
	t.Helper()
	if mapped[name] != expected {
		t.Fatalf("expected %s=%q, got %q", name, expected, mapped[name])
	}
}
