import {
  GENERATED_SECRET_KEYS,
  createGeneratedOpenSendEnv,
  renderOpenSendEnvFile,
  validateOpenSendEnv,
} from "@opensend/core/src/env";
import { describe, expect, it } from "vitest";

describe("OpenSend env bootstrap", () => {
  it("generates a complete production-shaped env without placeholder secrets", () => {
    const env = createGeneratedOpenSendEnv({
      appUrl: "https://mail.example.com",
    });

    for (const key of GENERATED_SECRET_KEYS) {
      expect(env[key], `${key} should be generated`).toBeTruthy();
      expect(env[key]).not.toContain("local-dev");
      expect(env[key]).not.toContain("replace-before-production");
    }

    expect(env.BETTER_AUTH_SECRET).toMatch(/^[a-f0-9]{64}$/);
    expect(env.WEBHOOK_SECRET_ENCRYPTION_KEY).toMatch(/^[a-f0-9]{64}$/);
    expect(env.INGESTER_JOB_TOKEN).toMatch(/^[a-f0-9]{64}$/);
    expect(Buffer.from(env.DKIM_ENCRYPTION_KEY, "base64")).toHaveLength(32);

    expect(
      validateOpenSendEnv(
        { ...env, NODE_ENV: "production" },
        { service: "app", production: true },
      ).errors,
    ).toEqual([]);
    expect(
      validateOpenSendEnv(
        { ...env, NODE_ENV: "production" },
        { service: "ingester", production: true },
      ).errors,
    ).toEqual([]);
    expect(
      validateOpenSendEnv(
        {
          ...env,
          NODE_ENV: "production",
          INGESTER_URL: "https://events.example.com",
        },
        { service: "scheduler", production: true },
      ).errors,
    ).toEqual([]);
  });

  it("renders all generated values into an env file", () => {
    const env = createGeneratedOpenSendEnv({
      appUrl: "http://localhost:3015",
      postgresPassword: "test-postgres-password",
      external: { AWS_REGION: "us-east-1" },
    });
    const rendered = renderOpenSendEnvFile(env);

    expect(rendered).toContain("# Generated by `bun run setup`.");
    expect(rendered).toContain(
      "DATABASE_URL=postgresql://opensend:test-postgres-password@localhost:5432/opensend",
    );
    expect(rendered).toContain(
      `DKIM_ENCRYPTION_KEY=${env.DKIM_ENCRYPTION_KEY}`,
    );
    expect(rendered).not.toContain("undefined");
  });

  it("reports every missing production app key in one validation result", () => {
    const result = validateOpenSendEnv(
      { NODE_ENV: "production" },
      { service: "app", production: true },
    );

    expect(result.errors.map((issue) => issue.key)).toEqual(
      expect.arrayContaining([
        "DATABASE_URL",
        "BETTER_AUTH_URL",
        "NEXT_PUBLIC_APP_URL",
        "BETTER_AUTH_SECRET",
        "BETTER_AUTH_TRUSTED_ORIGINS",
        "WEBHOOK_SECRET_ENCRYPTION_KEY",
        "TRACKING_SECRET",
        "UNSUBSCRIBE_SECRET",
        "DKIM_ENCRYPTION_KEY",
      ]),
    );
    expect(result.errors.length).toBeGreaterThanOrEqual(9);
  });
});
