import type { CompatibilityEntry, CompatibilityStatus } from "./types";

const sdkCall = (
  id: string,
  resend: string,
  opensend: string,
  status: CompatibilityStatus,
  evidence: string,
  caveats: string,
  patterns: readonly RegExp[],
): CompatibilityEntry => ({
  id,
  detectorKind: "sdk-call",
  resend,
  opensend,
  status,
  evidence,
  caveats,
  sdkPatterns: patterns,
});

const restEndpoint = (
  id: string,
  resend: string,
  opensend: string,
  status: CompatibilityStatus,
  evidence: string,
  caveats: string,
  patterns: readonly RegExp[],
): CompatibilityEntry => ({
  id,
  detectorKind: "rest-endpoint",
  resend,
  opensend,
  status,
  evidence,
  caveats,
  restPatterns: patterns,
});

const environment = (
  id: string,
  resend: string,
  opensend: string,
  status: CompatibilityStatus,
  evidence: string,
  caveats: string,
  patterns: readonly RegExp[],
): CompatibilityEntry => ({
  id,
  detectorKind: "environment",
  resend,
  opensend,
  status,
  evidence,
  caveats,
  envPatterns: patterns,
});

export const compatibilityMatrix: readonly CompatibilityEntry[] = [
  {
    id: "sdk-import-resend",
    detectorKind: "sdk-import",
    resend: "import/require from resend",
    opensend:
      "OpenSend TypeScript SDK exposes Resend and Opensend clients from the opensend package.",
    status: "partial",
    evidence:
      "agent_docs/resend-parity.md#TypeScript SDK; packages/sdk/src/index.ts",
    caveats:
      "Constructor and send-path compatibility exist, but OpenSend's TypeScript SDK does not cover every Resend SDK resource.",
    sdkPatterns: [
      /from\s+["']resend["']/g,
      /require\(\s*["']resend["']\s*\)/g,
      /from\s+["']@resend\//g,
    ],
  },
  sdkCall(
    "sdk-client-constructor",
    "new Resend(apiKey)",
    "new Resend(osApiKey, { baseUrl }) from the opensend SDK",
    "partial",
    "packages/sdk/src/index.ts; tests/sdk-client.test.tsx",
    "OpenSend accepts a Resend-compatible client class, but callers must install/import OpenSend's package and use an OpenSend API key/base URL.",
    [/new\s+Resend\s*\(/g],
  ),
  sdkCall(
    "emails-send",
    "resend.emails.send(...) / resend.emails.create(...)",
    "POST /emails",
    "full",
    "agent_docs/resend-parity.md#Single send; src/lib/openapi.ts; tests/api-emails.test.ts",
    "Static scan cannot prove payload-level compatibility; verify templates, attachments, tags, and scheduling in application tests.",
    [/\.emails\.(send|create)\s*\(/g],
  ),
  sdkCall(
    "emails-batch",
    "resend.batch.send(...) / resend.emails.sendBatch(...)",
    "POST /emails/batch",
    "partial",
    "agent_docs/resend-parity.md#Batch send; tests/api-emails.test.ts",
    "Batch endpoint exists and returns a Resend-shaped envelope; authenticated deployed proof and edge payloads remain caveated in parity docs.",
    [/\.batch\.send\s*\(/g, /\.emails\.sendBatch\s*\(/g],
  ),
  sdkCall(
    "emails-cancel",
    "resend.emails.cancel(id)",
    "POST /emails/{email_id}/cancel",
    "full",
    "agent_docs/resend-parity.md#Cancel scheduled send; src/app/emails/[id]/cancel/route.ts",
    "Only scheduled emails can be canceled; static scan cannot know runtime email state.",
    [/\.emails\.cancel\s*\(/g],
  ),
  sdkCall(
    "emails-update",
    "resend.emails.update(id, ...)",
    "PATCH /emails/{email_id}",
    "partial",
    "agent_docs/resend-parity.md#Scheduled send; public/docs/api-reference/emails/update-email.md",
    "Scheduled update support is present but natural-language scheduled_at compatibility has caveats.",
    [/\.emails\.update\s*\(/g],
  ),
  sdkCall(
    "emails-read",
    "resend.emails.get/list(...)",
    "GET /emails and GET /emails/{id}",
    "partial",
    "public/docs/api-reference/emails/list-emails.md; public/docs/api-reference/emails/retrieve-email.md",
    "OpenSend exposes sent-email reads, but dashboard/API route behavior and response breadth may differ from Resend.",
    [/\.emails\.(get|retrieve|list)\s*\(/g],
  ),
  sdkCall(
    "domains",
    "resend.domains.*",
    "OpenSend domains API",
    "partial",
    "agent_docs/resend-parity.md#Domains; public/docs/api-reference/domains",
    "Domain create/verify exists, but custom return-path and some provider-specific parity gaps remain.",
    [/\.domains\.(create|list|get|retrieve|update|delete|verify)\s*\(/g],
  ),
  sdkCall(
    "contacts",
    "resend.contacts.*",
    "OpenSend contacts API",
    "partial",
    "agent_docs/resend-parity.md#Contacts; src/app/contacts/route.ts",
    "Root contact aliases exist, but SDK/resource breadth and some audience semantics differ.",
    [/\.contacts\.(create|list|get|retrieve|update|delete)\s*\(/g],
  ),
  sdkCall(
    "audiences",
    "resend.audiences.*",
    "OpenSend segments/audience metadata APIs",
    "partial",
    "agent_docs/resend-parity.md#Audiences",
    "Resend audiences are deprecated but still live; OpenSend primarily models segments and does not provide full root audience parity.",
    [/\.audiences\.(create|list|get|retrieve|delete)\s*\(/g],
  ),
  sdkCall(
    "segments",
    "resend.segments.*",
    "OpenSend segments API",
    "partial",
    "agent_docs/resend-parity.md#Segments; src/app/segments/route.ts",
    "Segment services exist, but SDK/root response shape parity is incomplete.",
    [/\.segments\.(create|list|get|retrieve|delete|contacts)\s*\(/g],
  ),
  sdkCall(
    "broadcasts",
    "resend.broadcasts.*",
    "OpenSend broadcasts API",
    "partial",
    "agent_docs/resend-parity.md#Broadcasts; public/docs/api-reference/broadcasts",
    "Broadcast APIs exist but root alias and SDK parity are incomplete.",
    [/\.broadcasts\.(create|list|get|retrieve|update|delete|send)\s*\(/g],
  ),
  sdkCall(
    "templates",
    "resend.templates.*",
    "OpenSend templates API",
    "full",
    "agent_docs/resend-parity.md#Stored templates; public/docs/api-reference/templates",
    "Stored template endpoints are implemented; variable interpolation has separate partial caveats.",
    [
      /\.templates\.(create|list|get|retrieve|update|delete|publish|duplicate)\s*\(/g,
    ],
  ),
  sdkCall(
    "api-keys",
    "resend.apiKeys.*",
    "OpenSend API keys API",
    "full",
    "agent_docs/resend-parity.md#API keys API; public/docs/api-reference/api-keys",
    "API-key management requires a full-access OpenSend API key.",
    [
      /\.apiKeys\.(create|list|delete)\s*\(/g,
      /\.api_keys\.(create|list|delete)\s*\(/g,
    ],
  ),
  sdkCall(
    "webhooks",
    "resend.webhooks.*",
    "OpenSend webhooks API",
    "partial",
    "agent_docs/resend-parity.md#Webhooks; public/docs/api-reference/webhooks",
    "Webhook CRUD/filtering exists, but event-type coverage and dashboard replay have parity caveats.",
    [/\.webhooks\.(create|list|get|retrieve|update|delete)\s*\(/g],
  ),
  sdkCall(
    "suppressions",
    "resend.suppressions.*",
    "OpenSend suppressions API",
    "partial",
    "public/docs/api-reference/suppressions; agent_docs/resend-parity.md#Bounce / complaint feed",
    "OpenSend exposes suppression APIs, but historical parity notes still flag dashboard/feed gaps.",
    [/\.suppressions\.(list|delete|remove)\s*\(/g],
  ),
  sdkCall(
    "inbound-received-emails",
    "resend.emails.received.* / received emails SDK helpers",
    "OpenSend received-email APIs",
    "unknown",
    "public/docs/api-reference/emails/list-received-emails.md",
    "Received-email SDK helper parity is not proven by the v1 matrix; inspect OpenAPI and run application tests.",
    [/\.receivedEmails\./g, /\.emails\.received\./g],
  ),
  sdkCall(
    "mcp-resend",
    "resend MCP server package/configuration",
    "OpenSend MCP package",
    "unsupported",
    "agent_docs/resend-parity.md#MCP server; packages/mcp/package.json",
    "This verifier does not migrate MCP client configuration; OpenSend MCP is a separate package/configuration surface.",
    [/resend-mcp/g],
  ),
  restEndpoint(
    "rest-emails-send",
    "POST /emails",
    "POST /emails",
    "full",
    "agent_docs/resend-parity.md#Single send; public/docs/api-reference/emails/send-email.md",
    "Verify request body fields that use advanced attachments, React rendering, or schedule strings.",
    [/api\.resend\.com\/(?:v\d+\/)?emails(?![\w/-])/g, /["'`]\/emails["'`]/g],
  ),
  restEndpoint(
    "rest-emails-batch",
    "POST /emails/batch",
    "POST /emails/batch",
    "partial",
    "agent_docs/resend-parity.md#Batch send; public/docs/api-reference/emails/send-batch-emails.md",
    "Batch endpoint exists; static scan cannot prove idempotency or deployed quota behavior.",
    [
      /api\.resend\.com\/(?:v\d+\/)?emails\/batch/g,
      /["'`]\/emails\/batch["'`]/g,
    ],
  ),
  restEndpoint(
    "rest-emails-cancel",
    "POST /emails/{email_id}/cancel",
    "POST /emails/{email_id}/cancel",
    "full",
    "agent_docs/resend-parity.md#Cancel scheduled send",
    "Only scheduled emails are cancelable.",
    [
      /api\.resend\.com\/(?:v\d+\/)?emails\/[^\s"'`/]+\/cancel/g,
      /\/emails\/[^\s"'`/]+\/cancel/g,
    ],
  ),
  restEndpoint(
    "rest-contacts",
    "/contacts endpoints",
    "/contacts endpoints",
    "partial",
    "agent_docs/resend-parity.md#Contacts; public/docs/api-reference/contacts",
    "Contact CRUD is available, but SDK/resource and exact envelope parity remain caveated.",
    [
      /api\.resend\.com\/(?:v\d+\/)?contacts(?:\/[^\s"'`]*)?/g,
      /["'`]\/contacts(?:\/[^"'`]*)?["'`]/g,
    ],
  ),
  restEndpoint(
    "rest-segments",
    "/segments endpoints",
    "/segments endpoints",
    "partial",
    "agent_docs/resend-parity.md#Segments; public/docs/api-reference/segments",
    "Segment services exist, but root alias/SDK parity has caveats.",
    [
      /api\.resend\.com\/(?:v\d+\/)?segments(?:\/[^\s"'`]*)?/g,
      /["'`]\/segments(?:\/[^"'`]*)?["'`]/g,
    ],
  ),
  restEndpoint(
    "rest-domains",
    "/domains endpoints",
    "/domains endpoints",
    "partial",
    "agent_docs/resend-parity.md#Domains; public/docs/api-reference/domains",
    "Domain creation/verification exists; DNS/return-path behavior needs deployment validation.",
    [
      /api\.resend\.com\/(?:v\d+\/)?domains(?:\/[^\s"'`]*)?/g,
      /["'`]\/domains(?:\/[^"'`]*)?["'`]/g,
    ],
  ),
  restEndpoint(
    "rest-api-keys",
    "/api-keys endpoints",
    "/api-keys endpoints",
    "full",
    "agent_docs/resend-parity.md#API keys API; public/docs/api-reference/api-keys",
    "Requires full-access API key; do not expose keys in generated reports.",
    [
      /api\.resend\.com\/(?:v\d+\/)?api-keys(?:\/[^\s"'`]*)?/g,
      /["'`]\/api-keys(?:\/[^"'`]*)?["'`]/g,
    ],
  ),
  restEndpoint(
    "rest-broadcasts",
    "/broadcasts endpoints",
    "/broadcasts endpoints",
    "partial",
    "agent_docs/resend-parity.md#Broadcasts; public/docs/api-reference/broadcasts",
    "Broadcast APIs exist, but root alias/SDK parity is incomplete.",
    [
      /api\.resend\.com\/(?:v\d+\/)?broadcasts(?:\/[^\s"'`]*)?/g,
      /["'`]\/broadcasts(?:\/[^"'`]*)?["'`]/g,
    ],
  ),
  restEndpoint(
    "rest-templates",
    "/templates endpoints",
    "/templates endpoints",
    "full",
    "agent_docs/resend-parity.md#Stored templates; public/docs/api-reference/templates",
    "Template variable behavior has separate partial caveats.",
    [
      /api\.resend\.com\/(?:v\d+\/)?templates(?:\/[^\s"'`]*)?/g,
      /["'`]\/templates(?:\/[^"'`]*)?["'`]/g,
    ],
  ),
  restEndpoint(
    "rest-webhooks",
    "/webhooks endpoints",
    "/webhooks endpoints",
    "partial",
    "agent_docs/resend-parity.md#Webhooks; public/docs/api-reference/webhooks",
    "Webhook CRUD/filtering exists; event coverage and replay parity are partial.",
    [
      /api\.resend\.com\/(?:v\d+\/)?webhooks(?:\/[^\s"'`]*)?/g,
      /["'`]\/webhooks(?:\/[^"'`]*)?["'`]/g,
    ],
  ),
  restEndpoint(
    "rest-audiences",
    "/audiences endpoints",
    "OpenSend segments/audience metadata APIs",
    "partial",
    "agent_docs/resend-parity.md#Audiences",
    "OpenSend does not provide full root audience parity; prefer segments where possible.",
    [
      /api\.resend\.com\/(?:v\d+\/)?audiences(?:\/[^\s"'`]*)?/g,
      /["'`]\/audiences(?:\/[^"'`]*)?["'`]/g,
    ],
  ),
  restEndpoint(
    "rest-unknown-resend-api",
    "Unmapped api.resend.com endpoint",
    "No verified OpenSend equivalent in this v1 matrix",
    "unknown",
    "packages/migrate-from-resend/src/matrix.ts",
    "The scanner found Resend API usage that did not match a known v1 matrix endpoint. Inspect manually before claiming compatibility.",
    [
      /api\.resend\.com\/(?!(?:v\d+\/)?(?:emails|contacts|segments|domains|api-keys|broadcasts|templates|webhooks|audiences)(?:[\/\s"'`]|$))[^\s"'`]+/g,
    ],
  ),
  environment(
    "env-api-key",
    "RESEND_API_KEY",
    "OPENSEND_API_KEY",
    "full",
    "public/docs/api-reference/authentication.md",
    "Use an OpenSend `os_...` key; do not reuse a Resend `re_...` key.",
    [/RESEND_API_KEY/g],
  ),
  environment(
    "env-base-url",
    "RESEND_BASE_URL / https://api.resend.com",
    "OPENSEND_BASE_URL / your OpenSend origin",
    "full",
    "public/docs/api-reference/introduction.md",
    "Point REST clients at your OpenSend base URL, commonly https://opensend.namuh.co or your self-hosted origin.",
    [/RESEND_BASE_URL/g, /https:\/\/api\.resend\.com/g],
  ),
];

export const unknownCompatibilityEntry: CompatibilityEntry = {
  id: "unknown-resend-usage",
  detectorKind: "sdk-call",
  resend: "Unmapped Resend SDK usage",
  opensend: "No verified OpenSend equivalent in this v1 matrix",
  status: "unknown",
  evidence: "packages/migrate-from-resend/src/matrix.ts",
  caveats:
    "The scanner detected a Resend-shaped call outside the v1 matrix. Review manually and update the matrix when compatibility is known.",
};

export function summarizeStatuses(entries: readonly CompatibilityEntry[]) {
  return entries.reduce<Record<CompatibilityStatus, number>>(
    (counts, entry) => {
      counts[entry.status] += 1;
      return counts;
    },
    { full: 0, partial: 0, unsupported: 0, unknown: 0 },
  );
}
